### ISSUE TITLE
第一次弹出时数据不能完全显示，只显示一条的问题

### ISSUE THREAD

**Issue by MrFuShuai** [tonycheng93/PopWindow#1]
在适配器的getView()方法中应将条目数据绑定的操作放在if... else... 判断之后，而不是这个判断的里面
`@Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder = null;
        if (convertView == null) {
            convertView = LayoutInflater.from(mContext).inflate(R.layout.item_province_list, null, false);
            holder = new ViewHolder();
            holder.nameView = (TextView) convertView.findViewById(R.id.province_name);
            convertView.setTag(holder);
        }else {
            holder = (ViewHolder) convertView.getTag();
        }

        ProvinceList provinceList = mList.get(position);
        if (provinceList.getProvince_name() != null){
            holder.nameView.setText(provinceList.getProvince_name());
        }
        return convertView;
    }`

**Comment by tonycheng93** [comment]
@MrFuShuai 你是对的，我写的时候没注意，尴尬
